name: ojs-tools
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - beautifulsoup4=4.12.3
  - brotli-python=1.1.0
  - bs4=4.12.3
  - bzip2=1.0.8
  - ca-certificates=2024.2.2
  - certifi=2024.2.2
  - charset-normalizer=3.3.2
  - click=8.1.7
  - click-default-group=1.2.4
  - docformatter=1.7.5
  - elementpath=4.3.0
  - icu=73.2
  - idna=3.6
  - jinja2=3.1.3
  - ld_impl_linux-64=2.40
  - libblas=3.9.0
  - libcblas=3.9.0
  - libexpat=2.5.0
  - libffi=3.4.2
  - libgcc-ng=13.2.0
  - libgfortran-ng=13.2.0
  - libgfortran5=13.2.0
  - libgomp=13.2.0
  - libiconv=1.17
  - liblapack=3.9.0
  - libnsl=2.0.1
  - libopenblas=0.3.26
  - libsqlite=3.45.1
  - libstdcxx-ng=13.2.0
  - libuuid=2.38.1
  - libxcrypt=4.4.36
  - libxml2=2.12.5
  - libxslt=1.1.39
  - libzlib=1.2.13
  - lxml=5.1.0
  - markupsafe=2.1.5
  - ncurses=6.4
  - numpy=1.26.4
  - openssl=3.2.1
  - pandas=2.2.0
  - pip=24.0
  - pysocks=1.7.1
  - python=3.12.2
  - python-dateutil=2.8.2
  - python-tzdata=2024.1
  - python_abi=3.12
  - pytz=2024.1
  - readline=8.2
  - requests=2.31.0
  - ruff=0.2.2
  - setuptools=69.1.0
  - six=1.16.0
  - soupsieve=2.5
  - tk=8.6.13
  - toposort=1.10
  - typing-extensions=4.9.0
  - typing_extensions=4.9.0
  - tzdata=2024a
  - untokenize=0.1.1
  - urllib3=2.2.1
  - wheel=0.42.0
  - xmlschema=3.0.2
  - xsdata=24.2.1
  - xz=5.2.6
